# Form implementation generated from reading ui file 'd:\GitHubRepos\Plan-My-Day\assets\UI\date_time_popup.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=Dialog)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=Dialog)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.labelSelectedDateTime = QtWidgets.QLabel(parent=Dialog)
        self.labelSelectedDateTime.setObjectName("labelSelectedDateTime")
        self.verticalLayout.addWidget(self.labelSelectedDateTime)
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Date and Time"))
        self.labelTitle.setText(_translate("Dialog", "Please select the end date and time of the task"))
        self.dateTimeEdit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy HH:mm"))
        self.labelSelectedDateTime.setText(_translate("Dialog", "Selected date and time: "))
        self.okButton.setText(_translate("Dialog", "OK"))
